name: 'duckdb_iceberg'
version: '1.0.0'
config-version: 2

profile: 'duckdb_iceberg'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  duckdb_iceberg:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  raw_data_path: "{{ env_var('RAW_DATA_PATH', './data/raw') }}"
  iceberg_data_path: "{{ env_var('ICEBERG_DATA_PATH', './data/iceberg') }}"
