clickhouse_warehouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: dbt_dev  # ClickHouse database for dbt models
      host: localhost
      port: 8123
      user: dbt
      password: "dbt_development"  # Update with your dbt user password
      secure: false 